server:
  port: 8082
spring:
  kafka:
    bootstrap:
      servers: broker:9092
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
    topic:
      name: payments
#    bootstrap-servers: broker:9092
